### ISSUE TITLE
Archiving this module

### ISSUE THREAD

**Issue by zilchms** [voxpupuli/puppet-jenkins_job_builder#104]
The discussion came up of this module should get archived. Should someone want to keep this module around, just comment here.
If no comments to keep this around arise in the new weeks, we will move forward with archiving.

**Comment by bastelfreak** [comment]
We announced it on the mailinglist and will archive the module now. If someone is still interested in it please contact Vox Pupuli via our IRC channel #voxpupuli on Libera or our mailinglist [voxpupuli@groups.io](mailto:voxpupuli@groups.io).
