### ISSUE TITLE
Would it be possible to make install source configurable?

### ISSUE THREAD

**Issue by gregswift** [voxpupuli/puppet-jenkins_job_builder#17]
Fedora and EL7 both have support for installing JJB as RPMs. Is this something you'd be open for in this module?

**Comment by nibalizer** [comment]
I'm happy to have this feature.

**Comment by liamjbennett** [comment]
+1

**Comment by rackergs** [comment]
I will be getting to this.. :)

**Comment by madAndroid** [comment]
This should be fixed with #20
