### ISSUE TITLE
Is this module still needed?

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/puppet-jenkins_job_builder#33]
The official jenkins module has added this support.

https://github.com/jenkinsci/puppet-jenkins#experimental-types-and-providers

**Comment by madAndroid** [comment]
@jyaworski - Yes, I would say that there is still a need for this module - there's no indication that the `rtyler/jenkins` module is using the [Openstack Jenkins Job Builder](http://docs.openstack.org/infra/jenkins-job-builder/) at any point - the jobs that it's able to create are [based on ERB templates](https://github.com/jenkinsci/puppet-jenkins#managing-jenkins-jobs), not on YAML files.

**Comment by madAndroid** [comment]
As discussed previously, there is definitely still a need for this module, going to close this PR. This can potentially be revisited if `rtyler/jenkins` includes JJB support at some point.

**Comment by jyaworski** [comment]
Ping @jenkinsci/puppet-jenkins
